services:
  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-service
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@profile-db:5432/profile_db
    networks:
      - attendance_net

  db:
    image: postgres:15
    container_name: profile-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance_net

volumes:
  postgres_data:

networks:
  attendance_net:
    external: true